global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'metaspace-demo'
    static_configs:
      - targets: ['metaspace-demo:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s